### ISSUE TITLE
Folder mode

### ISSUE THREAD

**Issue by luckydonald** [sourcekris/uniextract#1]
It would be great if when given a folder as input it would search for all relevant archive types, and extract that into the download folder keeping the hierarchy.

E.g. `/inputfolder/foo/bar/archive.zip` would become `/outputfolder/foo/bar/file/archive/some_file_inside.txt`

**Comment by sourcekris** [comment]
Good FR, thanks I'll take a swing at it.

**Comment by sourcekris** [comment]
Should be implemented as of https://github.com/sourcekris/uniextract/commit/d2eb883ab7d49b8de29a75bf4645e511e33c1c0f

Usage for extract.py is now:

```
./extract.py -h
usage: extract.py [-h] (-e FILENAME | -a PATH) [-c] [-d PATH]

Extract Files.

optional arguments:
  -h, --help            show this help message and exit
  -e FILENAME, --extract FILENAME
                        The file to extract.
  -a PATH, --all PATH   Extract all archives in a folder.
  -c, --createsubfolders
                        Create subfolders named for the archive when extracting using the --all mode.
  -d PATH, --destination PATH
                        An optional output folder.

Please file bugs on the GitHub Issues. Thanks
```

So use flags `--all` to select the source folder and if you want it to create a subfolder per archive use `-c`. 

Alternatively use `-d` to dump all subfiles to one path.

e.g.

```shell

$ ls
0.a  1.AR7  TEST.NSK
$ file *
0.a:      current ar archive
1.AR7:    AR7 archive data
TEST.NSK: NaShrink archive data
$ extract -a . -c
Archive type: AR
Extracting to folder: ./0
Archive type: NSK
Extracting to folder: ./TEST
Archive type: AR7
Extracting to folder: ./1
$ ls
0  0.a  1  1.AR7  TEST  TEST.NSK
$ ls TEST
FIRST.TXT  SECOND.TXT  TEST.TXT
```

**Comment by luckydonald** [comment]
Will it be able to inspect subfolders with `--all`?

E.g.
```
input_folder/some_folder/file1.zip
input_folder/some_folder/subfolder/file2.zip
```
With
```
extract.py --createsubfolders --all input_folder/ --destination output_folder/
```
Resulting in
```
output_folder/some_folder/file1/cat.png
output_folder/some_folder/subfolder/file2/code_to_hack_the_nsa.bf
```
Or would that need a `--recursive` flag?
Which in fact, now that I think about it, could be easily mistaken for zip files inside of zip files being extracted, too. Hmm...

**Comment by sourcekris** [comment]
it would need more code i suspect. I'll take a look and open another FR for recursion.
